Repository BajajGirik/deal-finder, pull requests merged in 2023-08, with the labels that each got.

#20 fixed web_browser
  deal_finder/web_browser.py
Labels: bug

#19 Fix discord class
  deal_finder/discord_client.py
  deal_finder/main.py
  deal_finder/notification/discord.py
  deal_finder/notification/notification.py
Labels: bug

#16 Add product meta retrieval flow
  deal_finder/constants.py
  deal_finder/database/product_tracker.py
  deal_finder/discord_client.py
  deal_finder/jobs/__init__.py
  deal_finder/jobs/products_tracker.py
  deal_finder/main.py
  deal_finder/notification/discord.py
  deal_finder/notification/notification.py
  deal_finder/utils/__init__.py
  deal_finder/utils/product_meta_collector.py
  deal_finder/utils/transformer.py
  deal_finder/utils/url.py
  deal_finder/web_browser.py
Labels: enhancement

#22 Add chrome options
  deal_finder/web_browser.py
Labels: improvement

#23 Add hosting / docker configuration
  .dockerignore
  .gitignore
  Dockerfile
Labels: enhancement

#26 Database env handling
  .env.example
  deal_finder/database/database.py
Labels: improvement

#27 Discord Bot Commands
  deal_finder/constants.py
  deal_finder/database/product_tracker.py
  deal_finder/discord_client/__init__.py
  deal_finder/discord_client/client.py
  deal_finder/discord_client/product_tracker.py
  deal_finder/discord_client/tasks.py
  deal_finder/main.py
  deal_finder/utils/transformer.py
Labels: enhancement

#30 Limit products tracked by user
  deal_finder/constants.py
  deal_finder/database/product_tracker.py
  deal_finder/discord_client/product_tracker.py
  deal_finder/utils/discord.py
Labels: enhancement

#31 Fix amazon css selector
  deal_finder/utils/product_meta_collector.py
Labels: bug
